// ui/packages/frontend/src/components/ParameterNavigation.tsx
import { Link, useParams } from "react-router-dom";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { ChevronDown, Settings } from "lucide-react";

const parameterCategories = [
  {
    filter: "behavior",
    label: "Behavior & Control",
    description: "PID, brewing, temperature, and control settings",
  },
  {
    filter: "hardware",
    label: "Hardware Configuration",
    description: "Sensors, relays, display, and hardware settings",
  },
  {
    filter: "system",
    label: "System & Connectivity",
    description: "MQTT, power management, and system configuration",
  },
];

export function ParameterNavigation() {
  const { filter } = useParams<{ filter: string }>();
  const currentCategory = parameterCategories.find(
    (cat) => cat.filter === filter
  );

  return (
    <div className="flex items-center gap-2 mb-6">
      <Settings className="h-5 w-5 text-muted-foreground" />
      <span className="text-sm font-medium text-muted-foreground">
        Parameter Category:
      </span>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" className="justify-between min-w-[200px]">
            {currentCategory?.label || "Select Category"}
            <ChevronDown className="ml-2 h-4 w-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="start" className="w-80">
          {parameterCategories.map((category) => (
            <DropdownMenuItem key={category.filter} asChild>
              <Link
                to={`/config/${category.filter}`}
                className="flex flex-col items-start p-3 cursor-pointer"
              >
                <div className="font-medium">{category.label}</div>
                <div className="text-xs text-muted-foreground">
                  {category.description}
                </div>
              </Link>
            </DropdownMenuItem>
          ))}
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}

// ui/packages/frontend-svelte-kit/src/lib/components/ParameterNavigation.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import {
		DropdownMenu,
		DropdownMenuContent,
		DropdownMenuItem,
		DropdownMenuTrigger
	} from '$lib/components/ui/dropdown-menu';
	import Button from '$lib/components/ui/button/button.svelte';
	import { ChevronDown, Settings } from 'lucide-svelte';

	const parameterCategories = [
		{
			filter: 'behavior',
			label: 'Behavior & Control',
			description: 'PID, brewing, temperature, and control settings'
		},
		{
			filter: 'hardware',
			label: 'Hardware Configuration',
			description: 'Sensors, relays, display, and hardware settings'
		},
		{
			filter: 'system',
			label: 'System & Connectivity',
			description: 'MQTT, power management, and system configuration'
		}
	];

	let currentCategory: { filter: string; label: string; description: string } | undefined;
	page.subscribe((p) => {
		currentCategory = parameterCategories.find((cat) => cat.filter === p.params.filter);
	});
</script>

<div class="mb-6 flex items-center gap-2">
	<Settings class="text-muted-foreground h-5 w-5" />
	<span class="text-muted-foreground text-sm font-medium">Parameter Category:</span>

	<DropdownMenu>
		<DropdownMenuTrigger>
			<Button variant="outline" class="min-w-[200px] justify-between">
				{currentCategory?.label || 'Select Category'}
				<ChevronDown class="ml-2 h-4 w-4" />
			</Button>
		</DropdownMenuTrigger>
		<DropdownMenuContent align="start" class="w-80">
			{#each parameterCategories as category}
				<DropdownMenuItem>
					<a
						href={`/config/${category.filter}`}
						class="flex cursor-pointer flex-col items-start p-3"
					>
						<div class="font-medium">{category.label}</div>
						<div class="text-muted-foreground text-xs">{category.description}</div>
					</a>
				</DropdownMenuItem>
			{/each}
		</DropdownMenuContent>
	</DropdownMenu>
</div>
