// ui/packages/frontend/src/App.tsx
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { Layout } from "./components/Layout";
import { HomePage } from "./pages/HomePage";
import { ConfigPage } from "./pages/ConfigPage";
import { SystemPage } from "./pages/SystemPage";
import { AboutPage } from "./pages/AboutPage";
import { NotFoundPage } from "./pages/NotFoundPage";
import { Toaster } from "./components/ui/sonner";
import { ErrorBoundary } from "./components/ErrorBoundary";
import { basePath } from "@/lib/config";

function App() {
  return (
    <ErrorBoundary>
      <BrowserRouter
        basename={basePath === "/" ? undefined : basePath.replace(/\/$/, "")}
      >
        <Routes>
          <Route path="/" element={<Layout />}>
            <Route index element={<HomePage />} />
            <Route path="config/:filter" element={<ConfigPage />} />
            <Route path="system" element={<SystemPage />} />
            <Route path="about" element={<AboutPage />} />
            {/* Catch-all route for 404 pages */}
            <Route path="*" element={<NotFoundPage />} />
          </Route>
        </Routes>
        <Toaster />
      </BrowserRouter>
    </ErrorBoundary>
  );
}

export default App;

// ui/packages/frontend-svelte/src/App.svelte
<script lang="ts">
  import './app.css';
  import { Toaster } from 'svelte-sonner';
  import { onMount } from 'svelte';
  import { currentComponent, initRouter } from './lib/router';

  // Layout and Pages
  import Layout from './lib/components/Layout.svelte';
  import HomePage from './lib/components/pages/HomePage.svelte';
  import ConfigPage from './lib/components/pages/ConfigPage.svelte';
  import SystemPage from './lib/components/pages/SystemPage.svelte';
  import AboutPage from './lib/components/pages/AboutPage.svelte';
  import NotFoundPage from './lib/components/pages/NotFoundPage.svelte';

  // Initialize router on mount
  onMount(() => {
    initRouter();
  });
</script>

<Layout>
  {#if $currentComponent === 'home'}
    <HomePage />
  {:else if $currentComponent === 'config'}
    <ConfigPage />
  {:else if $currentComponent === 'system'}
    <SystemPage />
  {:else if $currentComponent === 'about'}
    <AboutPage />
  {:else}
    <NotFoundPage />
  {/if}
</Layout>

<Toaster />
