// ui/packages/frontend-svelte/src/lib/components/LiveStatusIndicator.svelte
<script lang="ts">
  import { Wifi, WifiOff } from '@lucide/svelte';
  import { isOnline } from '../stores/clever-coffee-store';
</script>

<div class="flex items-center gap-2 text-sm">
  <div class="flex items-center gap-1">
    {#if $isOnline}
      <Wifi class="h-4 w-4 text-green-600" />
      <span class="text-green-600 font-medium">Online</span>
      <div class="h-2 w-2 bg-green-500 rounded-full animate-pulse"></div>
    {:else}
      <WifiOff class="h-4 w-4 text-red-600" />
      <span class="text-red-600 font-medium">Offline</span>
      <div class="h-2 w-2 bg-red-500 rounded-full"></div>
    {/if}
  </div>
</div>

// ui/packages/frontend/src/components/LiveStatusIndicator.tsx
import { useCleverCoffee } from "@/context/useCleverCoffee";
import { Wifi, WifiOff } from "lucide-react";

export function LiveStatusIndicator() {
  const { isOnline } = useCleverCoffee();

  return (
    <div className="flex items-center gap-2 text-sm">
      <div className="flex items-center gap-1">
        {isOnline ? (
          <>
            <Wifi className="h-4 w-4 text-green-600" />
            <span className="text-green-600 font-medium">Online</span>
            <div className="h-2 w-2 bg-green-500 rounded-full animate-pulse" />
          </>
        ) : (
          <>
            <WifiOff className="h-4 w-4 text-red-600" />
            <span className="text-red-600 font-medium">Offline</span>
            <div className="h-2 w-2 bg-red-500 rounded-full" />
          </>
        )}
      </div>
    </div>
  );
}
